export const projects = [
  {
    id: 1,
    title: "Crimson Hotel",
    description:
      "Built a high-performance hotel website using Next.js, featuring SSG/SSR, headless CMS integration, GA4 tracking, SEO optimization, and cross-browser compatibility testing.",
    image: "/images/project-images/crimson-hotel.jpg",
    category: ["Next.js"],
    techStack: [
      "Next.js",
      "React.js",
      "Tailwind CSS",
      "Laravel",
      "Filament CMS",
      "REST API",
      "Google Analytics",
      "PageSpeed Insights",
      "BrowserStack",
    ],
    link: "https://www.crimsonhotel.com/",
    featured: true,
  },
  {
    id: 2,
    title: "Quest Hotel",
    description:
      "Built a high-performance hotel website using Next.js, featuring SSG/SSR, headless CMS integration, GA4 tracking, SEO optimization, and cross-browser compatibility testing.",
    image: "/images/project-images/quest.jpg",
    category: ["Next.js"],
    techStack: [
      "Next.js",
      "React.js",
      "Tailwind CSS",
      "Laravel",
      "Filament CMS",
      "REST API",
      "Google Analytics",
      "PageSpeed Insights",
      "BrowserStack",
    ],
    link: "https://www.questhotelsandresorts.com/",
  },
  {
    id: 3,
    title: "Mimosa Plus Golf",
    description:
      "Built a high-performance hotel website using Next.js, featuring SSG/SSR, headless CMS integration, GA4 tracking, SEO optimization, and cross-browser compatibility testing.",
    image: "/images/project-images/mimosa.jpg",
    category: ["Next.js"],
    techStack: [
      "Next.js",
      "React.js",
      "Tailwind CSS",
      "Laravel",
      "Filament CMS",
      "REST API",
      "Google Analytics",
      "PageSpeed Insights",
      "BrowserStack",
    ],
    link: "https://mimosaplusgolf.com/",
  },
  {
    id: 4,
    title: "Timberland Highlands Resort",
    description:
      "Built a high-performance hotel website using Next.js, featuring SSG/SSR, headless CMS integration, GA4 tracking, SEO optimization, and cross-browser compatibility testing.",
    image: "/images/project-images/timberland.jpg",
    category: ["Next.js"],
    techStack: [
      "Next.js",
      "React.js",
      "Tailwind CSS",
      "Laravel",
      "Filament CMS",
      "REST API",
      "Google Analytics",
      "PageSpeed Insights",
      "BrowserStack",
    ],
    link: "https://www.timberlandresort.com/",
  },
  {
    id: 5,
    title: "Grafik Hotel",
    description:
      "Built a high-performance hotel website using Next.js, featuring SSG/SSR, headless CMS integration, GA4 tracking, SEO optimization, and cross-browser compatibility testing.",
    image: "/images/project-images/grafik-hotel.jpg",
    category: ["Next.js"],
    techStack: [
      "Next.js",
      "React.js",
      "Tailwind CSS",
      "Laravel",
      "Filament CMS",
      "REST API",
      "Google Analytics",
      "PageSpeed Insights",
      "BrowserStack",
    ],
    link: "https://www.grafikhotels.com/",
  },
  {
    id: 6,
    title: "Angels Pizza",
    description:
      "Maintained and enhanced a large-scale Angular-based e-commerce website by implementing new features, fixing bugs, optimizing performance and SEO, integrating analytics, and supporting headless CMS-driven content updates to ensure a reliable and seamless user experience.",
    image: "/images/project-images/angels-pizza.jpg",
    category: ["Angular.js"],
    techStack: [
      "Angular.js",
      "Typescript",
      "SCSS & CSS",
      "Laravel",
      "Custom CMS",
      "REST API",
      "Google Analytics",
      "BrowserStack",
    ],
    link: "https://www.angelspizza.com.ph/",
  },
  {
    id: 7,
    title: "Paper Moon Cafe",
    description:
      "Maintained an Angular-based website by fixing bugs, implementing content and image updates through a custom CMS, and ensuring consistent performance, functionality, and cross-browser compatibility.",
    image: "/images/project-images/papermoon-cafe.jpg",
    category: ["Angular.js"],
    techStack: [
      "Angular.js",
      "Typescript",
      "SCSS & CSS",
      "Laravel",
      "Custom CMS",
      "Google Analytics",
      "REST API",
      "BrowserStack",
    ],
    link: "https://papermoon.com.ph/",
  },
];
